- name: cart
  hosts: cart.hiteshshop.online
  become: yes
  tasks:
    - name: disable and enable nodejs:18
      shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    - name : install nodejs
      dnf:
        name: nodejs
        state: present
    - name: add user roboshop
      user:
        name: roboshop
    - name: create app folder in root
      file:
        path: /app
        state: directory
    - name: download content
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp/cart.zip
    - name: Extract cart zip file
      unarchive:
        src: /tmp/cart.zip
        dest: /app

    - name: install dependencies
      npm:
        path: /app
    - name: configure cart service file
      copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
        remote_src: yes
    - name : system daemon_reload
      systemd:
        daemon_reload: yes
    - name: enable and start cart
      service:
        state: started
        enabled: yes
    
