---
- name: Setup and Configure Catalogue Service
  hosts: catalogue
  become: yes  # This allows the playbook to run with elevated privileges (sudo)

  tasks:
    - name: Disable Node module
      command: dnf module disable nodejs -y

    - name: Enable Node.js 18 module
      command: dnf module enable nodejs:18 -y

    - name: Install Node.js
      dnf:
        name: nodejs
        state: present

    - name: Add application user roboshop
      user:
        name: roboshop
        system: yes
        shell: /sbin/nologin

    - name: Create app directory
      file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download application code
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Extract application code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: true

    - name: Install application dependencies
      npm:
        path: /app

    - name: Setup systemd Catalogue Service
      template:
        src: catalogue.service.j2
        dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable and start Catalogue service
      service:
        name: catalogue
        enabled: yes
        state: started

    - name: Configure MongoDB repository
      copy:
        content: |
          [mongodb-org-4.2]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
          gpgcheck=0
          enabled=1
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB client
      dnf:
        name: mongodb-org-shell
        state: present

    - name: Load Schema
      shell: mongo --host mongodb.hiteshshop.online </app/schema/catalogue.js ansible
