- name: MongoDB configuration
  hosts: mongodb
  become: true
  tasks:
    - name: create a file
      copy:
        content: |
                  [mongodb-org-4.2]
                  name=MongoDB Repository
                  baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
                  gpgcheck=0
                  enabled=1
        dest: /etc/yum.repos.d/mongo.repo
    - name: install mongodb required version
      dnf:
        name: mongodb-org
        state: present
    - name: enable and start mongodb
      service:
        name: mongodb-org
        enabled: true
        state: started
    - name : update 127.0.0.1 to 0.0.0.0
      replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name : restart mongodb
      service:
        name: mongodb-org
        state: restarted

