- name: configuring payments
  hosts: payments
  become: yes
  tasks:
    - name: install some softwares related to python
      dnf:
        name: '{{item}}'
        state: present
      loop:
        - python36
        - gcc
        - python3-devel
  

